### ISSUE TITLE
Effect of cholesterol on lipid headgroup dynamics

### ISSUE THREAD

**Issue by ohsOllila** [hsantila/Corrtimes#1]
Recent publication (https://doi.org/10.1016/j.bpj.2018.10.024) using CHARMM36 simulations states that the cholesterol does not tilt the PC headgroup, in line with the results in, e.g., the NMRlipids I publication. However, the publication suggests that phospholipids to orient their polar headgroups toward the cholesterol without tilting the P-N angle. My feeling is that this would reduce the rotational dynamics of the headgroup. However, according to the effective correlation time experiments in the thesis of Tiago Ferreira (https://portal.research.lu.se/ws/files/5656969/3879121.pdf), the cholesterol reduces the dynamics of glycerol backbone, but not headgroup (fig. 5.5).
  
Therefore, the analysis of effective correlation times and dynamics of lipid headgroup upon addition of cholesterol especially from CHARMM36 simulations would be quite interesting.

**Comment by hsantila** [comment]
I have already analysed this from several force fields. I plotted the results for 0% vs 50% cholesterol for g1/g2/g3 carbons here: https://github.com/hsantila/Corrtimes/blob/master/manuscripts/figures/cholesterol/Teff_chol_change.pdf
You can see that qualitatively one gets the experimental slowdown also from the simulations. I would not look at these quantitatively.

As for alpha/beta/gamma, the results are more mixed, raw data here: https://github.com/hsantila/Corrtimes/blob/master/data/cholesterol/0_vs_50perchol.dat
The "delta" row indicates change T_eff(0%chol)- T_eff(50%)chol.

**Comment by markussmiettinen** [comment]
In this [pull request](fc43116) I propose to discuss the issue in the following manner:

*Also,  while CHARMM36 correctly shows no chance in $\tau_\mathrm{e}$ of the $\gamma$, $\beta$, and $\alpha$ carbons, it does predict a clearly non-zero $\Delta R_{1}$ for all three, indicative of some inaccuracies in the headgroup rotational dynamics. Such inaccuracies might affect the recent findings~\cite{leeb18} obtained using CHARMM36 that  (at least at small cholesterol concentrations) the headgroups of PCs neighbouring a cholesterol (within 6.6\,\AA) spend more time on top of the cholesterol than elsewhere; such arrested rotations should manifest on $\tau_\mathrm e$ and $R_1$.*

@ohsOllila: Do you find this ok?

**Comment by ohsOllila** [comment]
It seems good, but I should read the whole manuscript to properly comment.

**Comment by markussmiettinen** [comment]
This discussion is included in the current version of the manuscript, which Samuli has commented in the summer 2020. Thus I believe the issue can be safely closed.
