### ISSUE TITLE
Time scale for fastest exponential: 0.1 or 1.0 ps?

### ISSUE THREAD

**Issue by markussmiettinen** [hsantila/Corrtimes#16]
Tiago's 2015 paper states that "_spectral density was calculated by first fitting a sum of 71 exponentials having correlation times from 1 ps to 1 μs with logarithmic spacing_".

In the present project, we have also used 71 exponentials with logarithmic spacing, but the correlation times have been spread between **0.1 ps** and 1 μs.

I do not believe that this has any qualitative effect on our results. However, because our data have been saved every 10 ps or even every 100 ps, the modes that have τ < 1 ps are effectively just noise. This shows especially when we look at the weigths of these 71 components, as is done in the panel C of the current [Fig 3](Figs/R1_and_comp.pdf). In principle we can then simply cut the x-axis from 1 ps, however, as pointed out by @ohsOllila, this might confuse NMR people, who would expect the weights to sum up to one.

What are your opinions, should we recalculate the weights, but starting from 1 ps?

**Comment by ohsOllila** [comment]
One option is to integrate the weights below 10ps and put the sum to the 10ps, and start axis from there, and mention in the caption that 10ps point represents 10ps and faster timescales.

**Comment by markussmiettinen** [comment]
> One option is to integrate the weights below 10ps and put the sum to the 10ps, and start axis from there, and mention in the caption that 10ps point represents 10ps and faster timescales.

Yes. This will have the right sum of weights, but look cumbersome.

@hsantila: How much work would it be to recalculate the fits starting from 1 ps? If I understood it correctly, the slowest task is the calculation of the correlation functions, which, however, would not need to be redone, right?

**Comment by ohsOllila** [comment]
Why does it look cumbersome?

**Comment by markussmiettinen** [comment]
> Why does it look cumbersome?

Because there will be a big initial peak, so it will look like there is a lot of weight there, but this is not the case, as it is mostly noise. Which we have to explain in the caption. We have to also not take it into account in the sliding window averaging, and have to explain this too in the caption.

**Comment by ohsOllila** [comment]
I think that there is really a quite a lot of weight in these fast motions, which will be there also if you use 1 or 10 ps as a minimum time. For example, in Fig. 7 in https://doi.org/10.1021/acs.jpcb.8b02250 the weight for the fast (10ps or faster timescale) is approximately 0.15 for loop region. For disordered protein regions we observe weights of approximately 0.2 for this fast motion. Of course, with the used saving frequencies, we have to be careful in saying anything else than that this arises from timescales of 10ps or faster. Anyway, I think that the large weight for these timescales is real, not noise. You can also look at the correlation functions to see how much they drop during the first 10ps.

**Comment by markussmiettinen** [comment]
Maybe. I think it would be clearest to just recalculate starting from 1 ps.

**Comment by hsantila** [comment]
Recalculation in it self isn't (CPU) time consuming, maybe a week at max. But this will involve redoing the data analysis for figures 2-4 and the figures themselves which is tedious and will add another week or so depending on other projects.

**Comment by markussmiettinen** [comment]
I vote for the recalculation starting from 1 ps.

**Comment by hsantila** [comment]
I have now started redoing the analysis with the fitting starting from 1ps
