### ISSUE TITLE
Fig 3 (Timescales on headgroup segments)

### ISSUE THREAD

**Issue by markussmiettinen** [hsantila/Corrtimes#17]
Some comments on the [Fig 3](Figs/R1_and_comp.pdf):

~1. Add x-labels and tick marks on all decades (red scribbles in the attachment).~

2. Add spaces between axes titles and units (green scribbles). NOT DONE FOR X LABELS YET!

~3. Remove capitalization of axes titles (blue scribbles).~

~4. Add unit on axis title (orange scribble).~

![R1_and_comp](https://user-images.githubusercontent.com/5721866/79599628-1f0cfe00-80e6-11ea-9871-90679889a104.jpg)

Additional points:
- ~See what the outcome of issue #16 will be.~
- An idea, for maybe later similar plots: As we anyway do the time scale fits for all the lipids separately, why don't we use the outcomes to get **distributions** of time scales? That is, for each time scale we would calculate the **average** weight. This might allow us to get nicer, more readable, time scale distribution curves, without doing the sliding average, which we now had to resort on.

**Comment by hsantila** [comment]
See if ok now

**Comment by markussmiettinen** [comment]
Ok.
