### ISSUE TITLE
Fig 6 (Effect of drying on R1)

### ISSUE THREAD

**Issue by markussmiettinen** [hsantila/Corrtimes#19]
~1. Use inverted x-scale to match the style in NMRlipids I.~

2. Add temperatures of the 20 and 5 w/l experimental data to the caption.

~3. Add lipid type to the key.~

~4. Differentiate DLPC by using a different symbol.~

**Comment by markussmiettinen** [comment]
In panel B the Berger triangles should point to the left to be consistent with table C, and the other figures.

**Comment by hsantila** [comment]
It seems gnuplot does not allow left pointing triangles but I rotated them in inkscape, see if ok now

**Comment by markussmiettinen** [comment]
Ok.
