### ISSUE TITLE
Fig 2 (Teff and R1 under standard conditions)

### ISSUE THREAD

**Issue by markussmiettinen** [hsantila/Corrtimes#5]
1. To make the data better visible, double the height of the panels, and change the layout such that the Teff panels are on the left, and the R1 panels on the right. Keep the width of the panels fixed, such that the final plot will span two columns. See the attachment for a mock-up.

2. To the panels showing the tails, add segment labels corresponding to the sn-1 (palmitoyl) chain, and remove the labels for those segments for which we plot no data. See the blue scribbles on the attachment.

3. Remove the extra spaces in the ends of the x-axes. See the green scribbles on the attachment.

![fig2 001](https://user-images.githubusercontent.com/5721866/72885887-1a17f880-3d09-11ea-803e-66bdbf794a02.jpeg)

**Comment by markussmiettinen** [comment]
4. In the key:

- Experimental -> experiment
- remove '_T=_'

**Comment by markussmiettinen** [comment]
5. In the xlabels:

_g_ -> g

**Comment by markussmiettinen** [comment]
Some further comments on the (nice!) new figure.

6. Remove the 'A' and 'B', see the red scribbles. We can manage in the text without them, and in my opinion they make the plot look overtight.

7. Add more space between the top axis and the texts, see the blue scribbles.

8. Remove capitalization from the x-axis title, see green scribbles.

9. Make the Slipids symbol identical for both Teff and R1, see purple scribbles.

10. Remove the empty space on the R1 panels by adjusting the y axis, see the orange scribbles.



![Screenshot 2020-03-10 at 11 39 53 ](https://user-images.githubusercontent.com/5721866/76516874-83d89700-645c-11ea-9ae1-0aacc19c07a5.png)

**Comment by hsantila** [comment]
Better now?

to 12. maalisk. 2020 klo 12.31 Markus Miettinen (notifications@github.com)
kirjoitti:

**Comment by markussmiettinen** [comment]
> Better now?

Yes, the current [figure](manuscripts/figures/normalcond_2020_3.pdf) looks pretty good! One more idea has come to mind in the meanwhile:

11. We could maybe still improve by using [these Berger data at 300 K](https://zenodo.org/record/1402417#.Xpg7ji2B3OQ) from the Fuchs group. They would probably make the error bars on Berger more reasonably sized.

**Comment by ohsOllila** [comment]
I would consider making these figures to the page width (both tau_e and R_1 figure) and put the tau_e on top and R_1 on the bottom. It may be possible to reduce the height then to keep the size of total figure the same.

**Comment by hsantila** [comment]
The height was optimized to separate the data points in y so I don't think we can reduce that. You would increase the size in x to separate the data points in this direction too, or?

**Comment by ohsOllila** [comment]
Yes, I would increase it to separate datapoints and make it more readable. I have very hard time to understand the figure now.

**Comment by markussmiettinen** [comment]
> Yes, I would increase it to separate datapoints and make it more readable. I have very hard time to understand the figure now.

Is the problem that (simulation)  datapoints for neighboring segments get mixed?

If this is the problem, one possible improvement for readibility would be to use different background colors for neighboring segments. (For example, use a light gray background for odd and white background for even segments.)

**Comment by markussmiettinen** [comment]
> The height was optimized to separate the data points in y so I don't think we can reduce that. You would increase the size in x to separate the data points in this direction too, or?

I do not want to decrease the panel heights. However, this is the main plot of the paper, and contains a lot of data, so I would not mind using even the whole page for it.

**Comment by hsantila** [comment]
I'd rather increase the x-size than do an alternating shading since the
background color is tricky or impossible to do in xmgrace and I would have
to post edit it in.

ti 30. kesäk. 2020 klo 12.22 Markus Miettinen (notifications@github.com)
kirjoitti:

**Comment by ohsOllila** [comment]
>Is the problem that (simulation) datapoints for neighboring segments get mixed?

>If this is the problem, one possible improvement for readibility would be to use different background colors for neighboring >segments. (For example, use a light gray background for odd and white background for even segments.)

yes, this is the problem. Also, the lines look weird. After reading the text I understand what they are, but as first sight it looks like that there is something wrong in the printing of the figure. If there would be somekind of way to show the value must be above the minimum point (upward arrow for example), it might be better. Anyway, I think that the points and lines are too close to each others in x-direction.

**Comment by markussmiettinen** [comment]
> OHS: yes, this is the problem. [...] Anyway, I think that the points and lines are too close to each others in x-direction.
>
> HA: background color is tricky or impossible to do in xmgrace

Ok, let us try doubling the panels' x-sizes as Samuli suggested, while keeping the panels' y-sizes. If this is not enough to solve the issue, I'll do the plot in gnuplot using the shading.

> OHS: Also, the lines look weird. After reading the text I understand what they are, but as first sight it looks like that there is something wrong in the printing of the figure. If there would be somekind of way to show the value must be above the minimum point (upward arrow for example), it might be better.

I know exactly what you mean. We too were thinking of the upward-pointing arrow, but chose against it. I think the main reason was that an arrowhead would not indicate clearly enough the high error estimate compared to points that had a small upper error estimate. (Also, it might again be difficult to implement in xmgrace?)

**Comment by hsantila** [comment]
Hi,



ti 30. kesäk. 2020 klo 18.03 Markus Miettinen (notifications@github.com)
kirjoitti:

> OHS: yes, this is the problem. [...] Anyway, I think that the points and
> lines are too close to each others in x-direction.
>
> HA: background color is tricky or impossible to do in xmgrace
>
> Ok, let us try doubling the panels' x-sizes as Samuli suggested, while
> keeping the panels' y-sizes. If this is not enough to solve the issue, I'll
> do the plot in gnuplot using the shading.
>
yep, lets try extending in x first and then I can also try the shading if
you have some model script so I don't have to google everything.



> OHS: Also, the lines look weird. After reading the text I understand what
> they are, but as first sight it looks like that there is something wrong in
> the printing of the figure. If there would be somekind of way to show the
> value must be above the minimum point (upward arrow for example), it might
> be better.
>
> I know exactly what you mean. We too were thinking of the upward-pointing
> arrow, but chose against it. I think the main reason was that an arrowhead
> would not indicate clearly enough the high error estimate compared to
> points that had a small upper error estimate. (Also, it might again be
> difficult to implement in xmgrace?)
>
Yep, I remember discussing the arrow option but I think the consensus was
it would make the thing more confusing and crowded

**Comment by markussmiettinen** [comment]
I think all the issues have been settled in the current figure.
