### ISSUE TITLE
Figure 1 panels A and B show different curves

### ISSUE THREAD

**Issue by markussmiettinen** [hsantila/Corrtimes#55]
Does it bother anyone else (@ohsOllila, @hsantila) that the panels show different curves?

I find it unintuitive that we change two things from A to B: The way x-axis is plotted (log to linear) and the data we plot (idealized to MD).

Would it make sense to add also an idealized curve to B? (We would do this while the peer review is taking place.)

**Comment by hsantila** [comment]
It does not bother me as long as this is clearly stated in the caption
